### ISSUE TITLE
Endless loop on cache::insert() when the cache is full, if a duplicate key has previously been added with cache::insert()

### ISSUE THREAD

**Issue by audioMirror** [akashihi/stlcache#20]
This test code shows an endless loop.

`
#include < iostream>
#include <stlcache/stlcache.hpp>
#include <stlcache/policy_lru.hpp>
#include < string>

void testEndlessLoop() {
	typedef stlcache::cache<int, string, stlcache::policy_lru> CacheLRU;

	const int capacity = 10;
	const int duplicateEvery = 4;
	const int duplcateValue = -1;
	CacheLRU cache(capacity);

	cout << "stlcache STARTING endless-loop test\n";

	for (int i = 0; i < capacity * 10; i++) {
		bool doDuplicate = (i % duplicateEvery) == 0;
		int key = doDuplicate ? duplcateValue : i;
		string value = std::to_string(static_cast<unsigned long long>(key));
		cache.insert(key, value);
	}
	cout << "stlcache ENDING endless-loop test\n";
}

int main()
{
	testEndlessLoop();
}
`

The cause of the problem is that all the policy classes get corrupted if the same key is inserted twice.  The policy eventually provides a victim that is not in the cache, and the over-capacity cleanup endless loops.  I show the problem with the policy_lru, but it can happen on most (or perhaps all) policy types.

The solution is to either:

1. Change all the policy classes to handle an insert() on an existing key.  If the key exists, do a touch() and return, else insert it.
2. Or, change the cache::insert() method to not call policy::insert() if the key exists in the policy, but rather just touch().

**Comment by akashihi** [comment]
What a wonderful world would it be if everyone will make such beautiful issues!

Thank you very much for your test code and comprehensive explanation. PR #25 fixes this
