### ISSUE TITLE
Boost library is no longer optional

### ISSUE THREAD

**Issue by audioMirror** [akashihi/stlcache#21]
The README.md (and the stlcache::cache internal docs) says that Boost is optional except for testing.

This is no longer true.  The lock.hpp interface bring in Boost directly, and the stlcache.hpp brings in Boost indirectly by including all stlcache namespace headers.

These headers should be fixed so that Boost is only needed if one of the new Boost lock classes are needed.  For the old non-locking behavior, with a lock_none, it should be possible to use this library without Boost.

**Comment by akashihi** [comment]
Well, you are right. Actually _most_ part of the Boost is not needed anymore, as c++17 includes standard libraries, replacing optional and shared_mutex. I will keep multi_index for a while, but it will require explicit `USE_BOOST` definition.

#24 fixes this issue.
