### ISSUE TITLE
cache::erase() corrupts _currEntries if there is no item to erase.

### ISSUE THREAD

**Issue by audioMirror** [akashihi/stlcache#6]
The erase code is: 

`
size_type erase ( const key_type& x ) throw() {
            size_type ret=_storage.erase(x);
            _policy->remove(x);

            _currEntries--;

            return ret;
        }
`

If "ret" is 0, the _currEntries gets decremented incorrectly.  This shows up in an assert in the size() method.
Instead, the correct code should be:

`  
size_type erase ( const key_type& x ) throw() {
    size_type ret=_storage.erase(x);
    _policy->remove(x);

    _currEntries-=ret;

    return ret;
 }
`

**Comment by akashihi** [comment]
Should be fixed with https://github.com/akashihi/stlcache/pull/13
